name = "Planetary Factory"
author = "kc00l"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e3858829e1dc118c89135ca98e4c81d6fd01e6fbf1c80d73e02156c5ecececf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
