name = "Planetary Factory"
author = "kc00l"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2131e959e4a91f0d53cb7419ef4bb75327656a05397f5cb995e4d10f189220ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
