name = "Planetary Factory"
author = "kc00l"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a697def9e3fd6a8b535775cb320877df7bc5c10a5384e7fa709ce1603993c73e"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.109"
