#!/usr/bin/env python3
"""Assert the Create kinetic recipes the pack re-authors are closed, current and unambiguous.

ADR-0034's sweep is default-deny, so Create's own 653 grid recipes are removed and the pack
re-authors the handful it wants onto the Assembling Machine (ADR-0017). That re-authoring is
generated by `scripts/create-recipe-convert.py` from `data/create/recipe.json` and
`data/pack/create-substitutions.json`, and `scripts/create-recipe-extract.py` produces the corpus
from the pinned jar. This is the static half.

WHY IT IS NOT `test_grid_recipes.py` AGAIN. That check converts a whole corpus; this converter is
CLOSURE-DRIVEN. `create-substitutions.json` names wanted roots and the converter pulls in whatever
their recipes need, transitively -- so the property to assert is not "the corpus was converted"
but "the closure is CLOSED": every root arrived, and nothing the closure reaches was left
unclassified. A recipe conversion that quietly stops one hop short still emits valid JSON.

WHAT IT PROVES, and why each one is worth an assertion:

  - the emitted files are what the converter writes. Generated output is never hand-edited
    (ADR-0026), and an edited file survives every other check here. This one matters more than
    usual: the subtree replaced ten HAND-WRITTEN files that had drifted from each other on the
    same substitution, which is the failure the converter exists to end
  - EVERY WANTED ROOT ARRIVED. A root that resolves to nothing is a component the player cannot
    craft, and the only symptom is its absence from EMI
  - EVERY SUBSTITUTION WAS APPLIED. No emitted ingredient may be a name the table substitutes
    away -- a substitution that silently fails to fire leaves the unobtainable original in place,
    which is exactly what a default-deny sweep turns into an uncraftable recipe
  - EVERY TAG HAS A SOURCE. `#create:cogwheel` and `#create:belt_connector` are NOT tags -- both
    are plain items, and neither has a tag file in any installed jar. A `{"tag": ...}` naming a
    tag that does not exist matches nothing: the recipe loads, sits in EMI and never fires, with
    no error in any log. Four of the ten hand-written files this subtree replaced carried exactly
    that typo, copied from a `#minecraft:logs` ingredient
  - COUNTS ARE PRESERVED against Create's own recipe, so a substitution table edit cannot quietly
    re-cost the kinetic line
  - NO ITEM HAS TWO HAND ROUTES. The Personal Assembler's resolver picks a route with no cost
    model (`test_hand_resolver.py`), so a second `crafting` recipe for one output is ambiguity it
    cannot resolve. Create ships three such pairs here -- the two gearbox conversions and the
    large cogwheel's second route -- and `machine_only` is what settles them
  - the recipes fit the machine that accepts them, and their categories route to it

WHAT IT CANNOT PROVE is that the sweep kept them in a running game, or that the Personal Assembler
offers them -- claims about a loaded `RecipeManager` and a menu, which
`docs/testing/what-to-check.md` puts on a human at delivery.

WHAT IT DOES NOT TRY TO PROVE is that the parts work once crafted. Whether a water wheel turns or a
gearbox reverses rotation is Create's own functionality, tested by Create. This pack decides what a
component costs and whether it is reachable; it does not re-verify the mod it borrows from.

Usage: tests/factorio/test_create_recipes.py
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CORPUS = ROOT / "data/create/recipe.json"
SUBSTITUTIONS = ROOT / "data/pack/create-substitutions.json"
EMITTED = ROOT / "kubejs/data/planetaryfactory/recipe"
CATEGORY_MAP = ROOT / "data/pack/category-map.json"
CONVERTER = ROOT / "scripts/create-recipe-convert.py"
EXTRACTOR = ROOT / "scripts/create-recipe-extract.py"
MACHINES = ROOT / "kubejs/startup_scripts/machines.js"
MODS = ROOT / "mods"

# The subtree this check owns, which both other converters are taught to skip.
CREATE_SUBTREE = "assembling/create"
CREATE = EMITTED / CREATE_SUBTREE

# The surface these recipes land on. `recipe_survivors.js` admits it, which is what carries them
# through ADR-0034's sweep; `test_recipe_sweep.py` is what asserts that, not this file.
ASSEMBLING_TYPE = "gtceu:assembling"

# Every tag an emitted recipe is allowed to name, and where it comes from. Spelled out rather
# than scanned, for the reason the grid check spells out `OBTAINABLE`: a vanilla tag is not in any
# mod jar, so a jar scan would fail `#minecraft:logs` and pass nothing useful. The real failure
# this catches is the opposite one -- a `create:` tag that looks plausible and does not exist.
KNOWN_TAGS = {
    "#minecraft:logs": "vanilla, and what Terra's surface grows -- ADR-0016's Sapros trees. The "
                       "pack's fuel table reads the same tag (ADR-0047).",
}

failures = []


def check(condition, message):
    if not condition:
        failures.append(message)


def max_item_inputs():
    """`ASSEMBLING_IO[0]` in machines.js -- the Assembling Machine's item-input envelope.

    READ rather than restated, the same way `test_grid_recipes.py` reads it: a constant copied
    into a check that never opens the source cannot catch the source disagreeing with it.
    """
    found = re.search(r"const ASSEMBLING_IO = \[\s*(\d+)", MACHINES.read_text())
    check(found is not None,
          "machines.js declares no `const ASSEMBLING_IO = [` -- this check cannot tell whether "
          "the emitted recipes fit the machine that accepts them")
    return int(found.group(1)) if found else None


def ingredient_name(entry):
    """`{item: x}` or `{tag: y}` as the one string form the corpus and this check share."""
    if "item" in entry:
        return entry["item"]
    if "tag" in entry:
        return "#" + entry["tag"]
    return None


def inputs_of(recipe):
    return [(ingredient_name(e["content"]["ingredient"]), e["content"]["count"])
            for e in recipe.get("inputs", {}).get("item", [])]


def output_of(recipe):
    entry = recipe["outputs"]["item"][0]["content"]
    return ingredient_name(entry["ingredient"]), entry["count"]


def routed_categories():
    """The Factorio categories `category-map.json` routes to the Assembling Machine."""
    routes = json.loads(CATEGORY_MAP.read_text())["routes"]
    return {name for name, machine in routes.items() if machine == "assembling"}


def main():
    check(CREATE.is_dir(),
          "kubejs/data/planetaryfactory/recipe/assembling/create/ does not exist -- run "
          "scripts/create-recipe-convert.py")
    if not CREATE.is_dir():
        return report()

    corpus = json.loads(CORPUS.read_text())
    subs = json.loads(SUBSTITUTIONS.read_text())
    emitted = {p.stem: json.loads(p.read_text()) for p in sorted(CREATE.glob("*.json"))}

    # The corpus is generated too, and only from the jar -- which is gitignored (ADR-0024), so a
    # clean clone cannot run this half. Skipped rather than failed, and said out loud: a check
    # that silently does nothing is worse than one that is not there.
    if MODS.is_dir() and any(MODS.glob("create-*.jar")):
        extracted = subprocess.run([sys.executable, str(EXTRACTOR), "--check", "--quiet"])
        check(extracted.returncode == 0,
              "scripts/create-recipe-extract.py --check failed, so data/create/recipe.json is "
              "not what the pinned Create jar holds -- re-extract")
    else:
        print("note: no Create jar in mods/, so the corpus is not checked against it")

    converted = subprocess.run([sys.executable, str(CONVERTER), "--check", "--quiet"])
    check(converted.returncode == 0,
          "scripts/create-recipe-convert.py --check failed, so the emitted Create recipes are not "
          "what the converter writes. They are generated -- re-run it rather than editing them")

    # Every wanted root arrived. This is the closure's own property and nothing else asserts it.
    made_here = {output_of(recipe)[0] for recipe in emitted.values()}
    for root in sorted(subs["wanted"]):
        check(root in made_here,
              "create-substitutions.json wants `%s` and no emitted recipe outputs it. A wanted "
              "root that resolves to nothing reaches the player as a component missing from EMI, "
              "with nothing in any log" % root)

    substitute, keep = subs["substitute"], subs["keep"]
    limit = max_item_inputs()
    routed = routed_categories()

    for name, recipe in sorted(emitted.items()):
        source = corpus.get(name)
        check(source is not None,
              "create/%s.json has no row in data/create/recipe.json -- a generated file the "
              "corpus does not explain, so either the corpus was re-extracted without re-running "
              "the converter, or the file was hand-written" % name)
        if source is None:
            continue

        check(recipe["type"] == ASSEMBLING_TYPE,
              "create/%s.json is type %r, not %r -- `recipe_survivors.js` admits the pack's "
              "assembling surface and the sweep removes everything else"
              % (name, recipe["type"], ASSEMBLING_TYPE))

        category = recipe["data"]["factorio_category"]
        check(category in routed,
              "create/%s.json is category %r, which category-map.json does not route to the "
              "Assembling Machine" % (name, category))

        inputs = inputs_of(recipe)
        check(limit is None or len(inputs) <= limit,
              "create/%s.json has %d distinct item inputs and the Assembling Machine takes %s "
              "(ASSEMBLING_IO, machines.js). It would load and never match"
              % (name, len(inputs), limit))

        # Counts are preserved: substitution replaces one-for-one and only ever merges, so the
        # total number of ingredient units is invariant.
        emitted_units = sum(count for _, count in inputs)
        source_units = sum(entry["amount"] for entry in source["ingredients"])
        check(emitted_units == source_units,
              "create/%s.json asks for %d ingredient unit(s); Create's own recipe asks for %d. A "
              "substitution replaces one-for-one, so the total cannot move -- re-costing the "
              "kinetic line is a decision, not a conversion"
              % (name, emitted_units, source_units))

        item, count = output_of(recipe)
        check((item, count) == (source["result"], source["result_count"]),
              "create/%s.json outputs %s x%d, but the corpus says %s x%d"
              % (name, item, count, source["result"], source["result_count"]))

        for ingredient, _ in inputs:
            check(ingredient not in substitute,
                  "create/%s.json takes `%s`, which create-substitutions.json substitutes away. "
                  "The substitution did not fire, so an unobtainable name reached the emitted "
                  "recipe -- under ADR-0034's sweep that is a recipe the player cannot craft"
                  % (name, ingredient))
            if ingredient.startswith("#"):
                check(ingredient in KNOWN_TAGS,
                      "create/%s.json names the tag `%s`, which KNOWN_TAGS does not source. A tag "
                      "that does not exist matches NOTHING: the recipe loads, shows in EMI and "
                      "never fires, with no error. `create:cogwheel` and `create:belt_connector` "
                      "are items, not tags, and reading one as a tag is the typo this catches"
                      % (name, ingredient))

    # Rule: ONE ROUTE PER ITEM, of any category. Two hand recipes is the resolver's ambiguity, but
    # a hand recipe plus a machine one is still two EMI entries for the same block at the same
    # cost -- Create's `*_from_conversion` pairs are orientation swaps whose orientations both
    # craft directly here, so they buy nothing. Asserting only the hand case let all three ship.
    maker = {}
    for name, recipe in sorted(emitted.items()):
        item, _ = output_of(recipe)
        check(item not in maker,
              "`%s` is output by both create/%s.json and create/%s.json. Two routes to one item "
              "is two EMI entries for the same block, and if both are `crafting` the Personal "
              "Assembler's resolver has no cost model to choose between them -- skip one in "
              "create-substitutions.json, or declare it `machine_only` if the second route is "
              "genuinely the only way to reach something"
              % (item, maker.get(item, "?"), name))
        maker[item] = name

    # The decision tables still decide something. A row nothing reads is a rule left behind.
    for name, why in sorted(subs["skip"].items()):
        check(name not in emitted,
              "create/%s.json is emitted, but the skip table says: %s" % (name, why))
    for name in sorted(subs["machine_only"]):
        check(name not in emitted
              or emitted[name]["data"]["factorio_category"] == "advanced-crafting",
              "create-substitutions.json forces `%s` onto the machine, but the emitted recipe is "
              "category %r -- it would be planned by hand after all"
              % (name, emitted.get(name, {}).get("data", {}).get("factorio_category")))
    for tag in sorted(KNOWN_TAGS):
        used = any(tag == ingredient
                   for recipe in emitted.values() for ingredient, _ in inputs_of(recipe))
        check(used, "KNOWN_TAGS sources `%s`, which no emitted recipe names -- a row left behind "
                    "by a substitution table edit" % tag)
    for row in sorted(keep):
        used = any(row == entry["ingredient"]
                   for name in emitted for entry in corpus[name]["ingredients"])
        check(used, "create-substitutions.json `keep` names `%s`, which no converted recipe "
                    "takes" % row)

    # Nothing here re-makes something another subtree already emits: a second route to one item
    # is a progression escape, and both would sit in EMI.
    for path in sorted(EMITTED.rglob("*.json")):
        if path.relative_to(EMITTED).as_posix().startswith(CREATE_SUBTREE + "/"):
            continue
        other = json.loads(path.read_text())
        if other.get("type") != ASSEMBLING_TYPE:
            continue
        for entry in other.get("outputs", {}).get("item", []):
            item = ingredient_name(entry["content"]["ingredient"])
            check(item not in made_here,
                  "`%s` is output by both create/ and %s. A second route to one item is a "
                  "progression escape -- skip one in create-substitutions.json"
                  % (item, path.relative_to(EMITTED).as_posix()))

    return report(emitted)


def report(emitted=None):
    for failure in failures:
        print("FAIL: " + failure)
    if failures:
        print("\n%d failure(s)" % len(failures))
        return 1
    emitted = emitted or {}
    hand = sum(1 for recipe in emitted.values()
               if recipe["data"]["factorio_category"] == "crafting")
    print("ok: %d Create recipe(s) -- %d hand-craftable, %d machine-only; every wanted root "
          "arrived, every substitution fired and every tag has a source"
          % (len(emitted), hand, len(emitted) - hand))
    return 0


if __name__ == "__main__":
    sys.exit(main())
