#!/usr/bin/env python3
"""Assert Create: Power Grid's re-authored recipes are craftable, current and unduplicated (#172).

ADR-0034's sweep is default-deny, so Power Grid's own 112 recipes are removed and the pack
re-authors the 84 that sat on surfaces no block here executes. That re-authoring is generated by
`scripts/powergrid-recipe-convert.py` from `data/powergrid/recipe.json` and
`data/pack/grid-substitutions.json`. This is its static half.

WHAT IT PROVES, and why each one is worth an assertion:

  - the emitted files are what the converter writes. Generated output is never hand-edited
    (ADR-0026), and an edited file survives every other check here
  - COUNTS ARE PRESERVED. #172's conversion is "a shape becomes a list": the total number of
    ingredient units in an emitted recipe equals the total in Power Grid's own, because a
    substitution replaces one-for-one and only ever merges. This is the assertion that catches a
    substitution table edit quietly re-costing the grid line
  - EVERY INGREDIENT BOTTOMS OUT. An ingredient is obtainable only if some pack recipe outputs it
    or the table below says how the world gives it. This is the whole failure #172 was filed
    against -- under a default-deny sweep a vanilla-looking item is not obtainable just because
    it is vanilla, and an unobtainable ingredient reaches the player as a recipe in EMI that
    cannot be crafted, with nothing in any log
  - NO ITEM HAS TWO ROUTES. Four recipes are skipped because #148 already emits something that
    outputs the same block; a fifth appearing later would be a progression escape rather than an
    error, so it is asserted rather than hoped for
  - the recipes fit the machine that accepts them, and their categories route to it

WHAT IT CANNOT PROVE is that the sweep kept them in a running game, or that the Personal
Assembler offers the hand ones. Both are claims about a loaded `RecipeManager` and a menu, which
`docs/testing/what-to-check.md` puts on a human on delivery -- #172's world load.

Usage: tests/factorio/test_grid_recipes.py
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CORPUS = ROOT / "data/powergrid/recipe.json"
SUBSTITUTIONS = ROOT / "data/pack/grid-substitutions.json"
EMITTED = ROOT / "kubejs/data/planetaryfactory/recipe"
CATEGORY_MAP = ROOT / "data/pack/category-map.json"
CONVERTER = ROOT / "scripts/powergrid-recipe-convert.py"

MACHINES = ROOT / "kubejs/startup_scripts/machines.js"

# The grid subtree, which this check owns and the Factorio converter is taught to skip. Named
# once so the exclusion below is not four string literals across three files.
GRID_SUBTREE = "grid"
GRID = EMITTED / GRID_SUBTREE


def max_item_inputs():
    """`ASSEMBLING_IO[0]` in machines.js -- the Assembling Machine's item-input envelope.

    READ rather than restated. The converter carries its own copy so it can fail early, and a
    constant repeated in two files that never reads the source cannot catch them disagreeing with
    it: they drift together. This is the one place that binds both to what the machine actually
    registers, which is the repo's "cross-file references resolve" idiom.
    """
    found = re.search(r"const ASSEMBLING_IO = \[\s*(\d+)", MACHINES.read_text())
    check(found is not None,
          "machines.js declares no `const ASSEMBLING_IO = [` -- this check cannot tell whether "
          "the emitted recipes fit the machine that accepts them")
    return int(found.group(1)) if found else None

# What the world hands the player directly, for ingredients no pack recipe outputs. Every row is
# a claim about Terra's worldgen or a tag's contents, and it is spelled out because under a
# default-deny sweep "it is a vanilla item" is not a reason to believe it is obtainable -- the
# vanilla recipe that used to make it is gone.
OBTAINABLE = {
    "#c:raw_materials/iron": "Terra's iron ore drops it (ADR-0021's four).",
    "#c:raw_materials/copper": "Terra's copper ore drops it (ADR-0021's four).",
    "#minecraft:coals": "Terra's coal ore drops it (ADR-0021's four).",
    "minecraft:coal": "as `#minecraft:coals`.",
    "minecraft:cobblestone": "Terra's stone drops it; ADR-0021 keeps stone in the alphabet.",
    "#minecraft:logs": "what Terra's surface grows -- ADR-0016's Sapros trees.",
    "#c:plates/iron": "holds `gtceu:iron_plate`, which `recipe/iron_plate.json` smelts (#91).",
    "#c:plates/copper": "holds `gtceu:copper_plate`, which `recipe/copper_plate.json` smelts.",
    "#c:wires/copper": "holds `powergrid:wire`, which `assembling/copper_cable.json` emits (#148).",
    "#c:copper_coils": "holds `powergrid:copper_coil`, which `grid/copper_coil.json` emits (#172).",
}

# Ingredients that are NOT obtainable and are known not to be, with the ticket that fixes it.
# Recorded rather than tolerated: the check still fails the day an unlisted one appears, and this
# list is the difference between a gap someone chose and a gap nobody noticed.
KNOWN_BLOCKED = {
    "gtceu:steel_plate": "5 plates to 1, which no vanilla smelting recipe can express -- it "
                         "waits on the pack furnace's own count-bearing recipe type "
                         "(`category-map.json`, `smelting`). Predates #172.",
}

failures = []


def check(condition, message):
    if not condition:
        failures.append(message)


def ingredient_name(entry):
    """`{item: x}` or `{tag: y}` as the one string form both the corpus and this check use.

    Returns None for anything else. The pack emits two component-bearing research-pack outputs
    (`neoforge:components`) that name no plain item, and they are not ingredients of anything --
    skipping them here is why the reachability walk below does not have to model components.
    """
    if "item" in entry:
        return entry["item"]
    if "tag" in entry:
        return "#" + entry["tag"]
    return None


def emitted_recipes():
    """Every recipe the pack emits, as (path, parsed), across both converters' subtrees."""
    return [(p, json.loads(p.read_text())) for p in sorted(EMITTED.rglob("*.json"))]


def outputs_of(recipe):
    """The item names a recipe produces. Fluids are out of scope: nothing in grid/ takes one."""
    if recipe["type"] == "minecraft:smelting":
        return [recipe["result"]["id"]]
    names = [ingredient_name(e["content"]["ingredient"])
             for e in recipe.get("outputs", {}).get("item", [])]
    return [name for name in names if name is not None]


def inputs_of(recipe):
    if recipe["type"] == "minecraft:smelting":
        return [(ingredient_name(recipe["ingredient"]), 1)]
    pairs = [(ingredient_name(e["content"]["ingredient"]), e["content"]["count"])
             for e in recipe.get("inputs", {}).get("item", [])]
    return [pair for pair in pairs if pair[0] is not None]


def main():
    corpus = json.loads(CORPUS.read_text())
    subs = json.loads(SUBSTITUTIONS.read_text())
    routes = json.loads(CATEGORY_MAP.read_text())["routes"]
    envelope = max_item_inputs()

    check(GRID.is_dir(), "kubejs/data/planetaryfactory/recipe/grid/ does not exist -- run "
                         "scripts/powergrid-recipe-convert.py")
    if not GRID.is_dir():
        return report()

    # The generated files are the converter's, not a hand-edited copy of them.
    converter = subprocess.run([sys.executable, str(CONVERTER), "--check", "--quiet"],
                               capture_output=True, text=True)
    check(converter.returncode == 0,
          "scripts/powergrid-recipe-convert.py --check failed, so the emitted grid recipes are "
          "not what its inputs produce:\n" + (converter.stderr.strip() or converter.stdout.strip()))

    grid = {p.stem: json.loads(p.read_text()) for p in sorted(GRID.glob("*.json"))}
    check(len(grid) == len(corpus) - len(subs["skip"]),
          "grid/ holds %d recipe(s); the corpus has %d and skips %d"
          % (len(grid), len(corpus), len(subs["skip"])))

    for name, recipe in grid.items():
        source = corpus.get(name)
        check(source is not None,
              "grid/%s.json has no row in data/powergrid/recipe.json -- a generated file the "
              "corpus no longer explains" % name)
        if source is None:
            continue

        # Counts are preserved: substitution is one-for-one and only ever merges.
        want = sum(entry["amount"] for entry in source["ingredients"])
        got = sum(count for _, count in inputs_of(recipe))
        check(want == got,
              "grid/%s.json asks for %d ingredient unit(s); Power Grid's own recipe asks for %d. "
              "#172 converts a shape to a list and changes no count" % (name, got, want))

        check(outputs_of(recipe) == [source["result"]],
              "grid/%s.json outputs %s, but the corpus says %s"
              % (name, outputs_of(recipe), source["result"]))

        category = recipe["data"]["factorio_category"]
        check(routes.get(category) == "assembling",
              "grid/%s.json is category %r, which category-map.json does not route to the "
              "Assembling Machine" % (name, category))
        check(envelope is None or len(recipe["inputs"]["item"]) <= envelope,
              "grid/%s.json has %d distinct item inputs and the Assembling Machine takes %s "
              "(ASSEMBLING_IO, machines.js) -- it would load and never match"
              % (name, len(recipe["inputs"]["item"]), envelope))

    # No item has two routes: a skipped recipe's block is emitted elsewhere, and nothing else is.
    made_by = {}
    for path, recipe in emitted_recipes():
        for item in outputs_of(recipe):
            made_by.setdefault(item, []).append(path.relative_to(EMITTED).as_posix())
    # Narrowly: no block may be made BOTH by this converter and by the Factorio one. Duplicates
    # within a single converter are not escapes and are expected -- Factorio has three solid-fuel
    # recipes, and Power Grid's `*_from_conversion` rows turn a block into its own other variant.
    # What the skip table exists to stop is #148's `assembling/` recipe and a grid/ recipe both
    # outputting the same Power Grid block, which is two routes at two different costs.
    for item, paths in sorted(made_by.items()):
        from_grid = [p for p in paths if p.startswith(GRID_SUBTREE + "/")]
        from_corpus = [p for p in paths if not p.startswith(GRID_SUBTREE + "/")]
        check(not (from_grid and from_corpus),
              "`%s` is output by both the Factorio converter (%s) and the grid converter (%s). "
              "Two routes at two costs is a progression escape -- add a `skip` row to "
              "grid-substitutions.json" % (item, ", ".join(from_corpus), ", ".join(from_grid)))

    for name, reason in sorted(subs["skip"].items()):
        check(name not in grid, "grid/%s.json is emitted, but the skip table says: %s"
                                % (name, reason))
        result = corpus[name]["result"] if name in corpus else None
        check(result in made_by,
              "the skip table drops `%s` because something else outputs `%s`, but nothing does. "
              "Skipping it leaves the block uncraftable" % (name, result))

    # A `machine_only` row is what keeps the conversion recipes out of the hand graph, so the
    # cycle assertion below is only true while this one is. Asserted rather than assumed: the two
    # tables are edited together and a row that stopped taking effect would look like a passing
    # check rather than a cycle.
    for name in sorted(subs["machine_only"]):
        recipe = grid.get(name)
        check(recipe is not None,
              "grid-substitutions.json forces `%s` onto the machine, but it is not emitted" % name)
        if recipe is not None:
            check(recipe["data"]["factorio_category"] == "advanced-crafting",
                  "grid/%s.json is `machine_only` but emitted as %r -- as a hand recipe it closes "
                  "a cycle the Personal Assembler cannot escape"
                  % (name, recipe["data"]["factorio_category"]))

    # ONE HAND RECIPE PER ITEM, AND NO CYCLES, over the set the Personal Assembler actually
    # builds. `RuntimeHandRecipes` reads the loaded recipe manager and keeps every recipe stamped
    # `crafting`, so its graph is the corpus's hand recipes AND grid/'s together -- neither
    # `test_hand_resolver.py` (which reads only `data/factorio/recipe.json`) nor anything else
    # sees the union. `RecipeGraph` says a second recipe for an item means the first registered
    # wins, "an arbitrary answer, not a stable one", and `PlanResolver` has no cost model to break
    # a cycle: Power Grid's `*_from_conversion` rows turn a block into its other orientation, so
    # admitting both directions would make a gauge require the gauge it is making.
    hand_maker = {}
    hand_inputs = {}
    for path, recipe in emitted_recipes():
        if recipe.get("data", {}).get("factorio_category") != "crafting":
            continue
        where = path.relative_to(EMITTED).as_posix()
        for item in outputs_of(recipe):
            check(item not in hand_maker,
                  "`%s` has two hand recipes (%s and %s). The Personal Assembler picks the first "
                  "the recipe manager hands it, which is not the same one twice"
                  % (item, hand_maker.get(item, ("?", None))[0], where))
            hand_maker[item] = (where, recipe)
            hand_inputs[item] = [name for name, _ in inputs_of(recipe)]

    walking, settled = set(), set()

    def cycles_from(item, trail):
        if item in settled:
            return
        if item in walking:
            failures.append(
                "the hand recipes cycle: %s. A plan for any of these needs an item further down "
                "the same chain, and the resolver has no cost model to pick another route"
                % " -> ".join(trail + [item]))
            return
        walking.add(item)
        for need in hand_inputs.get(item, []):
            if need in hand_inputs:
                cycles_from(need, trail + [item])
        walking.discard(item)
        settled.add(item)

    for item in sorted(hand_inputs):
        cycles_from(item, [])

    # Every ingredient bottoms out in something the player can actually get.
    for path, recipe in emitted_recipes():
        for item, _ in inputs_of(recipe):
            if item in made_by or item in OBTAINABLE:
                continue
            where = path.relative_to(EMITTED).as_posix()
            check(item in KNOWN_BLOCKED,
                  "%s takes `%s`, which no pack recipe outputs and which neither OBTAINABLE nor "
                  "KNOWN_BLOCKED explains. Under ADR-0034's sweep an item is obtainable only if "
                  "the pack makes it or the world drops it" % (where, item))

    return report(grid)


def report(grid=None):
    """Print the outcome. `grid` is the already-parsed recipes, so the ok-line re-reads nothing."""
    for failure in failures:
        print("FAIL: " + failure)
    if failures:
        print("\n%d failure(s)" % len(failures))
        return 1
    grid = grid or {}
    hand = sum(1 for recipe in grid.values()
               if recipe["data"]["factorio_category"] == "crafting")
    print("ok: %d grid recipe(s) -- %d hand-craftable, %d machine-only; every ingredient reaches "
          "a source" % (len(grid), hand, len(grid) - hand))
    return 0


if __name__ == "__main__":
    sys.exit(main())
