#!/usr/bin/env python3
"""Assert Terra's five ore blocks still agree with everything that names them (ADR-0041).

The blocks are registered in Java, their amounts are extracted from Factorio, their sprites and
their assets are generated by two scripts, and GregTech's Miner finds them by a tag. That is five
places one ore has to be named in, and the failures are all quiet:

  - **A block with no amounts behind it.** `OreResource.java` and the extracted slice the mod loads
    must deal the same five keys. A block outside the slice throws at class-init; a resource in the
    slice that nothing registers is ore Terra can never place.
  - **A drop that drifts.** `OreResource.java` and `scripts/build-ore-assets.py` each state which
    item an ore pays out -- the mod for a player's draw, and nothing at all for an explosion. If they
    disagree, a patch pays one item by hand and a different one to TNT, which no check but this
    one would ever see.
  - **A stage with no sprite.** Eight blockstate variants, eight models, eight textures, per ore.
    Vanilla renders a missing model as the purple-and-black cube, which on an ore field means a
    player watching a patch turn into an error as they mine it.
  - **The tag GregTech actually scans.** `MinerLogic` reads NeoForge's `Tags.Blocks.ORES`, so
    `c:ores` is what decides whether rung 1's drill can see a pack-authored ore block at all. ADR-0041
    names this as the risk that gates the whole body, and it is one line of JSON to get wrong.
  - **A generated file edited by hand.** Both scripts' `--check` runs here, so a sprite or a
    blockstate edited in place is a failure rather than a thing that survives until the next
    regeneration silently reverts it.

Usage: tests/pack/test_ore_assets.py
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

SLICE = ROOT / "mod/src/main/resources/planetaryfactory_core/ore/amounts.json"
RESOURCE_JAVA = ROOT / "mod/src/main/java/com/planetaryfactory/core/ore/OreResource.java"
ASSETS = ROOT / "kubejs/assets/planetaryfactory"
DATA = ROOT / "kubejs/data"

# The tag GregTech's Miner scans. Not decoration: `MinerLogic` reads `Tags.Blocks.ORES`, which is
# this file, and a block missing from it is invisible to every drill on the ladder.
ORES_TAG = DATA / "c/tags/block/ores.json"


def java_resources(source):
    """The enum's five entries: corpus key and drop item."""
    return {
        key: drop
        for key, drop in re.findall(r'\w+\("([a-z_]+)",\s*"([a-z0-9_:]+)"\)', source)
    }


def script_drops():
    """The drops `scripts/build-ore-assets.py` writes into the loot tables."""
    source = (ROOT / "scripts/build-ore-assets.py").read_text()
    body = source[source.index("ORES = {"):source.index("# The tags every one")]
    return {
        key: drop
        for key, drop in re.findall(r'"([a-z]+)":\s*\{"drop":\s*"([a-z0-9_:]+)"', body)
    }


def main():
    failures = []
    slice_ = json.loads(SLICE.read_text())
    corpus = slice_["resources"]
    java = java_resources(RESOURCE_JAVA.read_text())
    drops = script_drops()

    if set(java) != set(corpus):
        failures.append(
            f"OreResource registers {sorted(java)} and the extracted slice deals {sorted(corpus)}"
        )
    if java != drops:
        for key in sorted(set(java) | set(drops)):
            if java.get(key) != drops.get(key):
                failures.append(
                    f"{key} drops {java.get(key)} by hand and {drops.get(key)} to an explosion"
                )

    stages = max((len(entry["stage_ratios"]) for entry in corpus.values()), default=0)
    if stages < 2:
        failures.append(f"the slice carries {stages} stages; there is nothing to render")

    for ore in sorted(java):
        block = f"{ore}_ore"
        blockstate = ASSETS / "blockstates" / f"{block}.json"
        if not blockstate.is_file():
            failures.append(f"{block} has no blockstate")
            continue
        variants = json.loads(blockstate.read_text())["variants"]
        if len(variants) != stages:
            failures.append(
                f"{block} has {len(variants)} blockstate variants against {stages} stages"
            )
        for stage in range(stages):
            key = f"stage={stage}"
            if key not in variants:
                failures.append(f"{block} has no variant for {key}")
                continue
            model_id = variants[key]["model"].split(":", 1)[1]
            model = ASSETS / "models" / f"{model_id}.json"
            if not model.is_file():
                failures.append(f"{block} {key} points at {model_id}, which does not exist")
                continue
            texture = json.loads(model.read_text())["textures"]["all"].split(":", 1)[1]
            if not (ASSETS / "textures" / f"{texture}.png").is_file():
                failures.append(f"{model_id} points at {texture}.png, which does not exist")

        lang = json.loads((ASSETS / "lang/en_us.json").read_text())
        if f"block.planetaryfactory.{block}" not in lang:
            failures.append(f"{block} has no name in en_us.json")

        loot = DATA / "planetaryfactory/loot_table/blocks" / f"{block}.json"
        if not loot.is_file():
            failures.append(f"{block} has no loot table, so every destruction logs a missing one")
        elif json.loads(loot.read_text()).get("pools"):
            # ADR-0041 rejects "a hand break taking one unit and destroying the remainder" because
            # it "hands the player a way to vandalise a patch for one ore". A loot table that pays
            # out is that route wearing TNT: a thousand-unit block gone for one free item. The
            # metered path is OreMining.drop, and it is the only one.
            failures.append(
                f"{block}'s loot table pays out -- an explosion would buy a whole block's amount "
                "for one item, which is the vandalism route ADR-0041 closed")

    if "tooltip.planetaryfactory.ore.jade.amount" not in json.loads(
            (ASSETS / "lang/en_us.json").read_text()):
        failures.append("the Jade line has no lang key, so the amount would render as a raw key")

    if not ORES_TAG.is_file():
        failures.append("no c:ores tag -- GregTech's Miner scans it, and would see no pack ore")
    else:
        tagged = set(json.loads(ORES_TAG.read_text())["values"])
        missing = {f"planetaryfactory:{ore}_ore" for ore in java} - tagged
        if missing:
            failures.append(f"{sorted(missing)} are outside c:ores, so no drill can see them")

    for script in ("build-ore-textures.py", "build-ore-assets.py"):
        run = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / script), "--check"],
            capture_output=True, text=True)
        if run.returncode != 0:
            failures.append(f"scripts/{script} --check: {run.stdout.strip() or run.stderr.strip()}")

    for index, failure in enumerate(failures, 1):
        print(f"FAIL {index}: {failure}")
    if failures:
        return 1
    print(f"ok   {len(java)} ore blocks x {stages} stages, drops agree, all in c:ores")
    return 0


if __name__ == "__main__":
    sys.exit(main())
