package com.planetaryfactory.core.smelting;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * What burns in a burner furnace, and for how many joules (ADR-0047, #187).
 *
 * <p><b>Default-deny.</b> An item burns only if the table has a row for it. Forge's vanilla burn
 * table is a default-allow alphabet -- planks, blaze rods, lava buckets -- and under ADR-0034's
 * sweep the pack does not have most of what it names and does not admit the rest; asking it was
 * #155's defect. The rows are Factorio's fuels joined onto {@code item-map.json}, generated by
 * {@code scripts/factorio-fuel-convert.py}.
 *
 * <p><b>Category-filtered.</b> Only {@code chemical} burns, which is the only category a Factorio
 * furnace accepts. Every reachable fuel is chemical today, so the filter currently excludes
 * nothing; it is here for the item that arrives later. {@code uranium-fuel-cell} is {@code nuclear}
 * and has a {@code fuel_value}, so without the filter #135 would make it furnace fuel by landing.
 *
 * <p><b>Item, then tag.</b> A row's target is one or the other, and an item id is asked first so a
 * future row for a specific log could not be shadowed by {@code minecraft:logs}.
 *
 * <p>Pure: no Minecraft types. The caller resolves a stack into an item id and its tag ids.
 */
public final class FuelTable {

    /** The one category a furnace burns. Factorio's own, not a name of ours. */
    public static final String CHEMICAL = "chemical";

    public static final FuelTable EMPTY = new FuelTable(List.of());

    private final Map<String, Long> byItem = new HashMap<>();
    private final Map<String, Long> byTag = new HashMap<>();

    public FuelTable(Collection<FuelRow> rows) {
        for (FuelRow row : rows) {
            if (!CHEMICAL.equals(row.fuelCategory())) {
                continue;
            }
            Map<String, Long> into = row.tag() ? byTag : byItem;
            Long clash = into.put(row.target(), row.fuelValue());
            if (clash != null && clash != row.fuelValue()) {
                // Two fuels on one target with different values is a question the table cannot
                // answer, and answering it by iteration order would make a furnace's rate depend
                // on a file listing. `tests/factorio/test_fuel_convert.py` catches it first.
                throw new IllegalArgumentException(
                        row.target() + " is two fuels at once: " + clash + " J and "
                                + row.fuelValue() + " J");
            }
        }
    }

    /**
     * What one of this item is worth, or 0 for anything the table does not name.
     *
     * @param itemId the stack's item id
     * @param tagIds the tags that stack carries, asked only when the item itself has no row
     */
    public long joules(String itemId, Collection<String> tagIds) {
        Long direct = byItem.get(itemId);
        if (direct != null) {
            return direct;
        }
        if (!byTag.isEmpty()) {
            for (String tag : tagIds) {
                Long viaTag = byTag.get(tag);
                if (viaTag != null) {
                    return viaTag;
                }
            }
        }
        return 0L;
    }

    /** Whether anything at all burns, which is what a table that failed to load looks like. */
    public boolean isEmpty() {
        return byItem.isEmpty() && byTag.isEmpty();
    }

    public int size() {
        return byItem.size() + byTag.size();
    }
}
